
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 
 */
public class ClassDetails extends javax.swing.JFrame {

    /**
     * Creates new form ClassDetails
     */
    private final JPopupMenu popupMenu = new JPopupMenu();
    private final JPopupMenu popupMenu2 = new JPopupMenu();
    private JMenuItem menuItem =null;
    public ClassDetails() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(900,680);
         createPopupMenu(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblClasID = new javax.swing.JLabel();
        txtClassID = new javax.swing.JTextField();
        lblShortName = new javax.swing.JLabel();
        txtClassNAme = new javax.swing.JTextField();
        lblClassName = new javax.swing.JLabel();
        txtShortName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassDetails = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCncel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlSchoolDetails = new javax.swing.JPanel();
        lblSchoolDetails = new javax.swing.JLabel();
        lblSchoolDetailsIcon = new javax.swing.JLabel();
        pnlTeacherDetails = new javax.swing.JPanel();
        lblTeacherDetails = new javax.swing.JLabel();
        lblTeacherDetailsIcon = new javax.swing.JLabel();
        pnlSubjectDetails = new javax.swing.JPanel();
        lblSubjectDetails = new javax.swing.JLabel();
        lblSubjectDetailsIcon = new javax.swing.JLabel();
        pnlClassDetails = new javax.swing.JPanel();
        lblClassDetails = new javax.swing.JLabel();
        lblClassDetailsIcon = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlGenerateTimeTable = new javax.swing.JPanel();
        lblGenerateTimeTable = new javax.swing.JLabel();
        lblGenerateTimeTableIcon = new javax.swing.JLabel();
        pnlViewTimeTable = new javax.swing.JPanel();
        lblViewTimeTable = new javax.swing.JLabel();
        lblViewTimeTableIcon = new javax.swing.JLabel();
        pnlLogOut = new javax.swing.JPanel();
        lblBooks6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 600));

        jPanel3.setBackground(new java.awt.Color(128, 81, 123));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("School Time Table Generator");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/userIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 475));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblClasID.setText("Class ID");

        txtClassID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassIDActionPerformed(evt);
            }
        });

        lblShortName.setText("Short Name");

        txtClassNAme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassNAmeActionPerformed(evt);
            }
        });

        lblClassName.setText("Class Name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClassName))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblClasID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblShortName)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClassID, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtShortName)
                            .addComponent(txtClassNAme))))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClasID))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassName)
                    .addComponent(txtClassNAme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShortName))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        tblClassDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblClassDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject ID", "Subject Name", "Short Name"
            }
        ));
        jScrollPane1.setViewportView(tblClassDetails);

        jPanel4.setBackground(new java.awt.Color(214, 197, 214));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Class Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddNew.setText(" Add New");
        btnAddNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCncel.setText("Cancel");
        btnCncel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCncelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCncel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAddNew)
                        .addGap(25, 25, 25)
                        .addComponent(btnEdit)
                        .addGap(25, 25, 25)
                        .addComponent(btnDelete)
                        .addGap(25, 25, 25)
                        .addComponent(btnCncel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        pnlSchoolDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSchoolDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSchoolDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSchoolDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSchoolDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSchoolDetails.setText("School Details");
        lblSchoolDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSchoolDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSchoolDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSchoolDetailsMouseClicked(evt);
            }
        });

        lblSchoolDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchoolDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        javax.swing.GroupLayout pnlSchoolDetailsLayout = new javax.swing.GroupLayout(pnlSchoolDetails);
        pnlSchoolDetails.setLayout(pnlSchoolDetailsLayout);
        pnlSchoolDetailsLayout.setHorizontalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSchoolDetailsLayout.setVerticalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSchoolDetails)
                .addGap(20, 20, 20))
        );

        pnlTeacherDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblTeacherDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblTeacherDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblTeacherDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblTeacherDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTeacherDetails.setText("Teacher Details");
        lblTeacherDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTeacherDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTeacherDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTeacherDetailsMouseClicked(evt);
            }
        });

        lblTeacherDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/teacherIcon.png"))); // NOI18N
        lblTeacherDetailsIcon.setText("\n");

        javax.swing.GroupLayout pnlTeacherDetailsLayout = new javax.swing.GroupLayout(pnlTeacherDetails);
        pnlTeacherDetails.setLayout(pnlTeacherDetailsLayout);
        pnlTeacherDetailsLayout.setHorizontalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTeacherDetailsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTeacherDetailsLayout.setVerticalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pnlSubjectDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSubjectDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSubjectDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSubjectDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSubjectDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubjectDetails.setText("Subject Details");
        lblSubjectDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSubjectDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSubjectDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSubjectDetailsMouseClicked(evt);
            }
        });

        lblSubjectDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubjectDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/sbjectIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlSubjectDetailsLayout = new javax.swing.GroupLayout(pnlSubjectDetails);
        pnlSubjectDetails.setLayout(pnlSubjectDetailsLayout);
        pnlSubjectDetailsLayout.setHorizontalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSubjectDetailsIcon)
                .addGap(18, 18, 18)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubjectDetailsLayout.setVerticalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubjectDetailsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubjectDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlClassDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblClassDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblClassDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblClassDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblClassDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClassDetails.setText("Class Details");
        lblClassDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClassDetails.setEnabled(false);
        lblClassDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblClassDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/classRoomIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlClassDetailsLayout = new javax.swing.GroupLayout(pnlClassDetails);
        pnlClassDetails.setLayout(pnlClassDetailsLayout);
        pnlClassDetailsLayout.setHorizontalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblClassDetailsIcon)
                .addGap(20, 20, 20)
                .addComponent(lblClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClassDetailsLayout.setVerticalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClassDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassDetails))
                .addGap(19, 19, 19))
        );

        lblDashboard.setBackground(new java.awt.Color(204, 204, 255));
        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(204, 204, 204));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setText("Dashboard");

        pnlGenerateTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblGenerateTimeTable.setBackground(new java.awt.Color(153, 0, 153));
        lblGenerateTimeTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblGenerateTimeTable.setForeground(new java.awt.Color(204, 204, 204));
        lblGenerateTimeTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGenerateTimeTable.setText("Generate Time Table");
        lblGenerateTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenerateTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGenerateTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerateTimeTableMouseClicked(evt);
            }
        });

        lblGenerateTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/genarateTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlGenerateTimeTableLayout = new javax.swing.GroupLayout(pnlGenerateTimeTable);
        pnlGenerateTimeTable.setLayout(pnlGenerateTimeTableLayout);
        pnlGenerateTimeTableLayout.setHorizontalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblGenerateTimeTableIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlGenerateTimeTableLayout.setVerticalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGenerateTimeTableIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenerateTimeTable))
                .addGap(19, 19, 19))
        );

        pnlViewTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblViewTimeTable.setBackground(new java.awt.Color(153, 0, 153));
        lblViewTimeTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblViewTimeTable.setForeground(new java.awt.Color(204, 204, 204));
        lblViewTimeTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewTimeTable.setText("View Time Table");
        lblViewTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblViewTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewTimeTableMouseClicked(evt);
            }
        });

        lblViewTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/viewTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlViewTimeTableLayout = new javax.swing.GroupLayout(pnlViewTimeTable);
        pnlViewTimeTable.setLayout(pnlViewTimeTableLayout);
        pnlViewTimeTableLayout.setHorizontalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblViewTimeTableIcon)
                .addGap(20, 20, 20)
                .addComponent(lblViewTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlViewTimeTableLayout.setVerticalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewTimeTableIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewTimeTable))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlLogOut.setBackground(new java.awt.Color(153, 0, 153));

        lblBooks6.setBackground(new java.awt.Color(153, 0, 153));
        lblBooks6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblBooks6.setForeground(new java.awt.Color(204, 204, 204));
        lblBooks6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBooks6.setText("Logout");
        lblBooks6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBooks6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBooks6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBooks6MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/logOutIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogOutLayout = new javax.swing.GroupLayout(pnlLogOut);
        pnlLogOut.setLayout(pnlLogOutLayout);
        pnlLogOutLayout.setHorizontalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogOutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(lblBooks6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlLogOutLayout.setVerticalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBooks6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlClassDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
            .addComponent(pnlLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(pnlLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClassIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassIDActionPerformed

    private void txtClassNAmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassNAmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassNAmeActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void lblSchoolDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSchoolDetailsMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lblSchoolDetailsMouseClicked

    private void lblSubjectDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubjectDetailsMouseClicked
        // TODO add your handling code here:
         SubjectDetailsForm subjectDetailsForm = new SubjectDetailsForm();
        subjectDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSubjectDetailsMouseClicked

    private void lblTeacherDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTeacherDetailsMouseClicked
        // TODO add your handling code here:
         TeacherDetailsForm teacherDetailsForm = new TeacherDetailsForm();
        teacherDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblTeacherDetailsMouseClicked

    private void lblGenerateTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerateTimeTableMouseClicked
        // TODO add your handling code here:
popupMenu.show(this,150,475);
    }//GEN-LAST:event_lblGenerateTimeTableMouseClicked

    private void lblViewTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewTimeTableMouseClicked
        // TODO add your handling code here:
         popupMenu.show(this,150,550);
        
    }//GEN-LAST:event_lblViewTimeTableMouseClicked

    private void lblBooks6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooks6MouseClicked
       LoginPage lpage = new LoginPage();
            lpage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_lblBooks6MouseClicked

    private void btnCncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCncelActionPerformed
         Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCncelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassDetails().setVisible(true);
            }
        });
    }
    
      private void createPopupMenu(JFrame frame){
        
    menuItem = new JMenuItem(  "Master time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
       // TeacherDetailsForm teacherDetailsForm = new TeacherDetailsForm();
      //  jPanel3.setVisible(true);
                    
       
                }
       
    });
        
        
    menuItem = new JMenuItem(  "Teacher wise time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
                   
                     // jPanel3.setVisible(true);
       
                }
       
    });
  
    
      menuItem = new JMenuItem(  "Class wise time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
        ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
       
                }
    
       
    });
        menuItem = new JMenuItem(  "Create Master time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
        ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
       
                }
    
       
    });
       
     
     popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Master time table");
     popupMenu.add(menuItem);
    
      popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Teacher wise time table");
     popupMenu.add(menuItem);
    
      popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Class wise time table");
     popupMenu.add(menuItem);
    
        menuItem = new JMenuItem(  "Master time table");
     popupMenu2.add(menuItem);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCncel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBooks6;
    private javax.swing.JLabel lblClasID;
    private javax.swing.JLabel lblClassDetails;
    private javax.swing.JLabel lblClassDetailsIcon;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblGenerateTimeTable;
    private javax.swing.JLabel lblGenerateTimeTableIcon;
    private javax.swing.JLabel lblSchoolDetails;
    private javax.swing.JLabel lblSchoolDetailsIcon;
    private javax.swing.JLabel lblShortName;
    private javax.swing.JLabel lblSubjectDetails;
    private javax.swing.JLabel lblSubjectDetailsIcon;
    private javax.swing.JLabel lblTeacherDetails;
    private javax.swing.JLabel lblTeacherDetailsIcon;
    private javax.swing.JLabel lblViewTimeTable;
    private javax.swing.JLabel lblViewTimeTableIcon;
    private javax.swing.JPanel pnlClassDetails;
    private javax.swing.JPanel pnlGenerateTimeTable;
    private javax.swing.JPanel pnlLogOut;
    private javax.swing.JPanel pnlSchoolDetails;
    private javax.swing.JPanel pnlSubjectDetails;
    private javax.swing.JPanel pnlTeacherDetails;
    private javax.swing.JPanel pnlViewTimeTable;
    private javax.swing.JTable tblClassDetails;
    private javax.swing.JTextField txtClassID;
    private javax.swing.JTextField txtClassNAme;
    private javax.swing.JTextField txtShortName;
    // End of variables declaration//GEN-END:variables
}
