
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Prabuddi Sathyanka
 */
public class GenarateTimeTable extends javax.swing.JFrame {

    /**
     * Creates new form GenarateTimeTable
     */
        private final JPopupMenu popupMenu = new JPopupMenu();
     private final JPopupMenu popupMenu2 = new JPopupMenu();
    private JMenuItem menuItem =null;
    public GenarateTimeTable() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(900,680);
         createPopupMenu(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlSchoolDetails = new javax.swing.JPanel();
        lblSchoolDetails = new javax.swing.JLabel();
        lblSchoolDetailsIcon = new javax.swing.JLabel();
        pnlTeacherDetails = new javax.swing.JPanel();
        lblTeacherDetails = new javax.swing.JLabel();
        lblTeacherDetailsIcon = new javax.swing.JLabel();
        pnlSubjectDetails = new javax.swing.JPanel();
        lblSubjectDetails = new javax.swing.JLabel();
        lblSubjectDetailsIcon = new javax.swing.JLabel();
        pnlClassDetails = new javax.swing.JPanel();
        lblClassDetails = new javax.swing.JLabel();
        lblClassDetailsIcon = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlGenerateTimeTable = new javax.swing.JPanel();
        lblGenerateTimeTable = new javax.swing.JLabel();
        lblGenerateTimeTableIcon = new javax.swing.JLabel();
        pnlViewTimeTable = new javax.swing.JPanel();
        lblBooks5 = new javax.swing.JLabel();
        lblViewTimeTableIcon = new javax.swing.JLabel();
        pnlLogOut = new javax.swing.JPanel();
        lblBooks6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(214, 197, 214));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Generate Time Table");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("Generate Master Time Table");

        jLabel15.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 51));
        jLabel15.setText("Generate Relief Time Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(656, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(128, 81, 123));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("School Time Table Generator");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/userIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        pnlSchoolDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSchoolDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSchoolDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSchoolDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSchoolDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSchoolDetails.setText("School Details");
        lblSchoolDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSchoolDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSchoolDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchoolDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        javax.swing.GroupLayout pnlSchoolDetailsLayout = new javax.swing.GroupLayout(pnlSchoolDetails);
        pnlSchoolDetails.setLayout(pnlSchoolDetailsLayout);
        pnlSchoolDetailsLayout.setHorizontalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSchoolDetailsLayout.setVerticalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblSchoolDetails)
                .addGap(20, 20, 20))
        );

        pnlTeacherDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblTeacherDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblTeacherDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblTeacherDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblTeacherDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTeacherDetails.setText("Teacher Details");
        lblTeacherDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTeacherDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTeacherDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTeacherDetailsMouseClicked(evt);
            }
        });

        lblTeacherDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/teacherIcon.png"))); // NOI18N
        lblTeacherDetailsIcon.setText("\n");

        javax.swing.GroupLayout pnlTeacherDetailsLayout = new javax.swing.GroupLayout(pnlTeacherDetails);
        pnlTeacherDetails.setLayout(pnlTeacherDetailsLayout);
        pnlTeacherDetailsLayout.setHorizontalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTeacherDetailsIcon)
                .addGap(20, 20, 20)
                .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTeacherDetailsLayout.setVerticalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pnlSubjectDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSubjectDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSubjectDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSubjectDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSubjectDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubjectDetails.setText("Subject Details");
        lblSubjectDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSubjectDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSubjectDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSubjectDetailsMouseClicked(evt);
            }
        });

        lblSubjectDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubjectDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/sbjectIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlSubjectDetailsLayout = new javax.swing.GroupLayout(pnlSubjectDetails);
        pnlSubjectDetails.setLayout(pnlSubjectDetailsLayout);
        pnlSubjectDetailsLayout.setHorizontalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSubjectDetailsIcon)
                .addGap(18, 18, 18)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubjectDetailsLayout.setVerticalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubjectDetailsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubjectDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlClassDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblClassDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblClassDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblClassDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblClassDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClassDetails.setText("Class Details");
        lblClassDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClassDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblClassDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClassDetailsMouseClicked(evt);
            }
        });

        lblClassDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/classRoomIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlClassDetailsLayout = new javax.swing.GroupLayout(pnlClassDetails);
        pnlClassDetails.setLayout(pnlClassDetailsLayout);
        pnlClassDetailsLayout.setHorizontalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblClassDetailsIcon)
                .addGap(20, 20, 20)
                .addComponent(lblClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClassDetailsLayout.setVerticalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClassDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassDetails))
                .addGap(19, 19, 19))
        );

        lblDashboard.setBackground(new java.awt.Color(204, 204, 255));
        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(204, 204, 204));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setText("Dashboard");

        pnlGenerateTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblGenerateTimeTable.setBackground(new java.awt.Color(153, 0, 153));
        lblGenerateTimeTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblGenerateTimeTable.setForeground(new java.awt.Color(204, 204, 204));
        lblGenerateTimeTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGenerateTimeTable.setText("Generate Time Table");
        lblGenerateTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenerateTimeTable.setEnabled(false);
        lblGenerateTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGenerateTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerateTimeTableMouseClicked(evt);
            }
        });

        lblGenerateTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/genarateTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlGenerateTimeTableLayout = new javax.swing.GroupLayout(pnlGenerateTimeTable);
        pnlGenerateTimeTable.setLayout(pnlGenerateTimeTableLayout);
        pnlGenerateTimeTableLayout.setHorizontalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblGenerateTimeTableIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlGenerateTimeTableLayout.setVerticalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGenerateTimeTableIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenerateTimeTable))
                .addGap(19, 19, 19))
        );

        pnlViewTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblBooks5.setBackground(new java.awt.Color(153, 0, 153));
        lblBooks5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblBooks5.setForeground(new java.awt.Color(204, 204, 204));
        lblBooks5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBooks5.setText("View Time Table");
        lblBooks5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBooks5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBooks5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBooks5MouseClicked(evt);
            }
        });

        lblViewTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/viewTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlViewTimeTableLayout = new javax.swing.GroupLayout(pnlViewTimeTable);
        pnlViewTimeTable.setLayout(pnlViewTimeTableLayout);
        pnlViewTimeTableLayout.setHorizontalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblViewTimeTableIcon)
                .addGap(20, 20, 20)
                .addComponent(lblBooks5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlViewTimeTableLayout.setVerticalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewTimeTableIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBooks5))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlLogOut.setBackground(new java.awt.Color(153, 0, 153));

        lblBooks6.setBackground(new java.awt.Color(153, 0, 153));
        lblBooks6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblBooks6.setForeground(new java.awt.Color(204, 204, 204));
        lblBooks6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBooks6.setText("Logout");
        lblBooks6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBooks6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBooks6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBooks6MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/logOutIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogOutLayout = new javax.swing.GroupLayout(pnlLogOut);
        pnlLogOut.setLayout(pnlLogOutLayout);
        pnlLogOutLayout.setHorizontalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogOutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblBooks6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogOutLayout.setVerticalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBooks6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlClassDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
            .addComponent(pnlLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(pnlLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSubjectDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubjectDetailsMouseClicked
        // TODO add your handling code here:
         SubjectDetailsForm subjectDetailsForm;
         subjectDetailsForm = new SubjectDetailsForm();
        subjectDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSubjectDetailsMouseClicked

    private void lblClassDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClassDetailsMouseClicked
        // TODO add your handling code here:
        ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblClassDetailsMouseClicked

    private void lblTeacherDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTeacherDetailsMouseClicked
        // TODO add your handling code here:
         TeacherDetailsForm teacherDetailsForm = new TeacherDetailsForm();
        teacherDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblTeacherDetailsMouseClicked

    private void lblGenerateTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerateTimeTableMouseClicked
        // TODO add your handling code here:
        popupMenu.show(this,150,475);
    }//GEN-LAST:event_lblGenerateTimeTableMouseClicked

    private void lblBooks5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooks5MouseClicked
        // TODO add your handling code here:
         popupMenu.show(this,150,550);
    }//GEN-LAST:event_lblBooks5MouseClicked

    private void lblBooks6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooks6MouseClicked
         LoginPage lpage = new LoginPage();
            lpage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_lblBooks6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenarateTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenarateTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenarateTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenarateTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenarateTimeTable().setVisible(true);
            }
        });
    }
    
        private void createPopupMenu(JFrame frame){
        
    menuItem = new JMenuItem(  "Master time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
       // TeacherDetailsForm teacherDetailsForm = new TeacherDetailsForm();
      //  jPanel3.setVisible(true);
                    
       
                }
       
    });
        
        
    menuItem = new JMenuItem(  "Teacher wise time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
                   
                     // jPanel3.setVisible(true);
       
                }
       
    });
  
    
      menuItem = new JMenuItem(  "Class wise time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
        ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
       
                }
    
       
    });
        menuItem = new JMenuItem(  "Create Master time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
        ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
       
                }
    
       
    });
       
     
     popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Master time table");
     popupMenu.add(menuItem);
    
      popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Teacher wise time table");
     popupMenu.add(menuItem);
    
      popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Class wise time table");
     popupMenu.add(menuItem);
    
        menuItem = new JMenuItem(  "Master time table");
     popupMenu2.add(menuItem);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBooks5;
    private javax.swing.JLabel lblBooks6;
    private javax.swing.JLabel lblClassDetails;
    private javax.swing.JLabel lblClassDetailsIcon;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblGenerateTimeTable;
    private javax.swing.JLabel lblGenerateTimeTableIcon;
    private javax.swing.JLabel lblSchoolDetails;
    private javax.swing.JLabel lblSchoolDetailsIcon;
    private javax.swing.JLabel lblSubjectDetails;
    private javax.swing.JLabel lblSubjectDetailsIcon;
    private javax.swing.JLabel lblTeacherDetails;
    private javax.swing.JLabel lblTeacherDetailsIcon;
    private javax.swing.JLabel lblViewTimeTableIcon;
    private javax.swing.JPanel pnlClassDetails;
    private javax.swing.JPanel pnlGenerateTimeTable;
    private javax.swing.JPanel pnlLogOut;
    private javax.swing.JPanel pnlSchoolDetails;
    private javax.swing.JPanel pnlSubjectDetails;
    private javax.swing.JPanel pnlTeacherDetails;
    private javax.swing.JPanel pnlViewTimeTable;
    // End of variables declaration//GEN-END:variables
}

