
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Prabuddi Sathyanka
 */
public class SchoolDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form SchoolDetailsForm
     */
    public SchoolDetailsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.setSize(900,680);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlSchoolDetails = new javax.swing.JPanel();
        lblSchoolDetails = new javax.swing.JLabel();
        lblSchoolDetailsIcon = new javax.swing.JLabel();
        pnlTeacherDetails = new javax.swing.JPanel();
        lblTeacherDetails = new javax.swing.JLabel();
        lblTeacherDetailsIcon = new javax.swing.JLabel();
        pnlSubjectDetails = new javax.swing.JPanel();
        lblSubjectDetails = new javax.swing.JLabel();
        lblSubjectDetailsIcon = new javax.swing.JLabel();
        pnlClassDetails = new javax.swing.JPanel();
        lblClassDetails = new javax.swing.JLabel();
        lblClassDetailsIcon = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlGenerateTimeTable = new javax.swing.JPanel();
        lblGenerateTimeTable = new javax.swing.JLabel();
        lblGenerateTimeTableIcon = new javax.swing.JLabel();
        pnlViewTimeTable = new javax.swing.JPanel();
        lblViewTimeTable = new javax.swing.JLabel();
        lblViewTimeTableIcon = new javax.swing.JLabel();
        pnlLogOut = new javax.swing.JPanel();
        lblBooks6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblAcedemicYear = new javax.swing.JLabel();
        txtAcedemicYear = new javax.swing.JTextField();
        lblBellTimes = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkbxMonday = new javax.swing.JCheckBox();
        chkbxTuesday = new javax.swing.JCheckBox();
        chkbxThursday = new javax.swing.JCheckBox();
        chkbxWedensday = new javax.swing.JCheckBox();
        chkbxFriday = new javax.swing.JCheckBox();
        lblAcedemicYear1 = new javax.swing.JLabel();
        txtschoolname = new javax.swing.JTextField();
        btnAdd1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtend = new javax.swing.JTextField();
        txtstart = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();
        btnCncel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(128, 81, 123));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("School Time Table Generator");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/userIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        pnlSchoolDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSchoolDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSchoolDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSchoolDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSchoolDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSchoolDetails.setText("School Details");
        lblSchoolDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSchoolDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSchoolDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSchoolDetailsMouseClicked(evt);
            }
        });

        lblSchoolDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchoolDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        javax.swing.GroupLayout pnlSchoolDetailsLayout = new javax.swing.GroupLayout(pnlSchoolDetails);
        pnlSchoolDetails.setLayout(pnlSchoolDetailsLayout);
        pnlSchoolDetailsLayout.setHorizontalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSchoolDetailsLayout.setVerticalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblSchoolDetails)
                .addGap(20, 20, 20))
        );

        pnlTeacherDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblTeacherDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblTeacherDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblTeacherDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblTeacherDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTeacherDetails.setText("Teacher Details");
        lblTeacherDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTeacherDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTeacherDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTeacherDetailsMouseClicked(evt);
            }
        });

        lblTeacherDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/teacherIcon.png"))); // NOI18N
        lblTeacherDetailsIcon.setText("\n");

        javax.swing.GroupLayout pnlTeacherDetailsLayout = new javax.swing.GroupLayout(pnlTeacherDetails);
        pnlTeacherDetails.setLayout(pnlTeacherDetailsLayout);
        pnlTeacherDetailsLayout.setHorizontalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTeacherDetailsIcon)
                .addGap(18, 18, 18)
                .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTeacherDetailsLayout.setVerticalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pnlSubjectDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSubjectDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSubjectDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSubjectDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSubjectDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubjectDetails.setText("Subject Details");
        lblSubjectDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSubjectDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSubjectDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSubjectDetailsMouseClicked(evt);
            }
        });

        lblSubjectDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubjectDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/sbjectIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlSubjectDetailsLayout = new javax.swing.GroupLayout(pnlSubjectDetails);
        pnlSubjectDetails.setLayout(pnlSubjectDetailsLayout);
        pnlSubjectDetailsLayout.setHorizontalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSubjectDetailsIcon)
                .addGap(27, 27, 27)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubjectDetailsLayout.setVerticalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubjectDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pnlClassDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblClassDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblClassDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblClassDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblClassDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClassDetails.setText("Class Details");
        lblClassDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClassDetails.setEnabled(false);
        lblClassDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblClassDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/classRoomIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlClassDetailsLayout = new javax.swing.GroupLayout(pnlClassDetails);
        pnlClassDetails.setLayout(pnlClassDetailsLayout);
        pnlClassDetailsLayout.setHorizontalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblClassDetailsIcon)
                .addGap(28, 28, 28)
                .addComponent(lblClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClassDetailsLayout.setVerticalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClassDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassDetails))
                .addGap(19, 19, 19))
        );

        lblDashboard.setBackground(new java.awt.Color(204, 204, 255));
        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(204, 204, 204));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setText("Dashboard");

        pnlGenerateTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblGenerateTimeTable.setBackground(new java.awt.Color(153, 0, 153));
        lblGenerateTimeTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblGenerateTimeTable.setForeground(new java.awt.Color(204, 204, 204));
        lblGenerateTimeTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGenerateTimeTable.setText("Generate Time Table");
        lblGenerateTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenerateTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGenerateTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerateTimeTableMouseClicked(evt);
            }
        });

        lblGenerateTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/genarateTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlGenerateTimeTableLayout = new javax.swing.GroupLayout(pnlGenerateTimeTable);
        pnlGenerateTimeTable.setLayout(pnlGenerateTimeTableLayout);
        pnlGenerateTimeTableLayout.setHorizontalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblGenerateTimeTableIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlGenerateTimeTableLayout.setVerticalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGenerateTimeTableIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenerateTimeTable, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );

        pnlViewTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblViewTimeTable.setBackground(new java.awt.Color(153, 0, 153));
        lblViewTimeTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblViewTimeTable.setForeground(new java.awt.Color(204, 204, 204));
        lblViewTimeTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewTimeTable.setText("View Time Table");
        lblViewTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblViewTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewTimeTableMouseClicked(evt);
            }
        });

        lblViewTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/viewTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlViewTimeTableLayout = new javax.swing.GroupLayout(pnlViewTimeTable);
        pnlViewTimeTable.setLayout(pnlViewTimeTableLayout);
        pnlViewTimeTableLayout.setHorizontalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblViewTimeTableIcon)
                .addGap(18, 18, 18)
                .addComponent(lblViewTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlViewTimeTableLayout.setVerticalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewTimeTableIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewTimeTable))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlLogOut.setBackground(new java.awt.Color(153, 0, 153));

        lblBooks6.setBackground(new java.awt.Color(153, 0, 153));
        lblBooks6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblBooks6.setForeground(new java.awt.Color(204, 204, 204));
        lblBooks6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBooks6.setText("Logout");
        lblBooks6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBooks6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBooks6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBooks6MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/logOutIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogOutLayout = new javax.swing.GroupLayout(pnlLogOut);
        pnlLogOut.setLayout(pnlLogOutLayout);
        pnlLogOutLayout.setHorizontalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogOutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(lblBooks6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlLogOutLayout.setVerticalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBooks6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlClassDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
            .addComponent(pnlLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 475));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAcedemicYear.setText("School Name");

        txtAcedemicYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcedemicYearActionPerformed(evt);
            }
        });

        lblBellTimes.setText("Bell Times");

        lblStartTime.setText("Start");

        lblEndTime.setText("End");

        jLabel2.setText("School Days");

        chkbxMonday.setText("Monday");
        chkbxMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxMondayActionPerformed(evt);
            }
        });

        chkbxTuesday.setText("Tuesday");
        chkbxTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxTuesdayActionPerformed(evt);
            }
        });

        chkbxThursday.setSelected(true);
        chkbxThursday.setText("Thursday");
        chkbxThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxThursdayActionPerformed(evt);
            }
        });

        chkbxWedensday.setText("Wendsday");
        chkbxWedensday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxWedensdayActionPerformed(evt);
            }
        });

        chkbxFriday.setText("Friday");
        chkbxFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxFridayActionPerformed(evt);
            }
        });

        lblAcedemicYear1.setText("Acedemic Year");

        txtschoolname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtschoolnameActionPerformed(evt);
            }
        });

        btnAdd1.setText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtendActionPerformed(evt);
            }
        });

        txtstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(lblBellTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))
                                    .addComponent(lblAcedemicYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(chkbxMonday)
                                                    .addComponent(chkbxTuesday)
                                                    .addComponent(chkbxThursday)
                                                    .addComponent(chkbxWedensday)
                                                    .addComponent(chkbxFriday))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAdd1))
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(txtstart, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAcedemicYear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtschoolname, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 38, Short.MAX_VALUE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblAcedemicYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtend, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(131, 131, 131))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcedemicYear)
                    .addComponent(txtschoolname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcedemicYear1)
                    .addComponent(txtAcedemicYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBellTimes)
                    .addComponent(lblStartTime)
                    .addComponent(lblEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnAdd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chkbxMonday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbxTuesday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbxWedensday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbxThursday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbxFriday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(28, 28, 28))
        );

        jPanel4.setBackground(new java.awt.Color(214, 197, 214));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("School Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddNew.setText(" Add New");
        btnAddNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnCncel.setText("Cancel");
        btnCncel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCncelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCncel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAddNew)
                        .addGap(30, 30, 30)
                        .addComponent(btnCncel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSchoolDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSchoolDetailsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblSchoolDetailsMouseClicked

    private void lblTeacherDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTeacherDetailsMouseClicked
        // TODO add your handling code here:
        TeacherDetailsForm teacherDetailsForm = new TeacherDetailsForm();
        teacherDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblTeacherDetailsMouseClicked

    private void lblSubjectDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubjectDetailsMouseClicked
        // TODO add your handling code here:
        SubjectDetailsForm subjectDetailsForm = null;
        subjectDetailsForm = new SubjectDetailsForm();
        subjectDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSubjectDetailsMouseClicked

    private void lblGenerateTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerateTimeTableMouseClicked
        // TODO add your handling code here:
        //popupMenu.show(this,150,475);
    }//GEN-LAST:event_lblGenerateTimeTableMouseClicked

    private void lblViewTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewTimeTableMouseClicked
        // TODO add your handling code here:
       // popupMenu.show(this,150,550);

    }//GEN-LAST:event_lblViewTimeTableMouseClicked

    private void txtAcedemicYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcedemicYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcedemicYearActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        String schoolname = txtschoolname.getText();
        String schoolyear=txtAcedemicYear.getText();
        
        
       ResultSet rs = null;
       PreparedStatement ps;       
        
           try {
            String query="INSERT INTO `school_details`(`schoolName`, `acedemicYear`) VALUES (?,?)";
             ps = MyConnection.getConnection().prepareStatement(query);
           
             ps.setString(1,schoolname);
             ps.setString(2,schoolyear);
                    
                   
            
            if(ps.executeUpdate() > 0)
            {
            JOptionPane.showMessageDialog(null,"School details added successfully");            
            
             txtschoolname.setText(""); 
            txtAcedemicYear.setText("");
            }
            
           
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }       
           
       
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void chkbxTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxTuesdayActionPerformed
         String days;
        days="tuesday";
    }//GEN-LAST:event_chkbxTuesdayActionPerformed

    private void btnCncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCncelActionPerformed
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCncelActionPerformed

    private void lblBooks6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooks6MouseClicked
        LoginPage lpage = new LoginPage();
            lpage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_lblBooks6MouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String days = null;
        
        ResultSet rs = null;
        PreparedStatement ps;  
           try {
            String query="INSERT INTO `schooldays`(`days`) VALUES (?)";
             ps = MyConnection.getConnection().prepareStatement(query);
           
             ps.setString(1,days);
            
            
            if(ps.executeUpdate() > 0)
            {
            JOptionPane.showMessageDialog(null,"School details added successfully");            
          }
            
           
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }       
               
               
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtschoolnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtschoolnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtschoolnameActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        String start1 = txtstart.getText();
        String start2 = txtend.getText();
               
       ResultSet rs = null;
       PreparedStatement ps;       
        
           try {
            String query="INSERT INTO `bell_times`(`start_time`, `end_time`) VALUES (?,?)";
             ps = MyConnection.getConnection().prepareStatement(query);
           
             ps.setString(1,start1);
             ps.setString(2,start2);
            
            if(ps.executeUpdate() > 0)
            {
            JOptionPane.showMessageDialog(null,"School details added successfully");            
          }
            
           
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }       
               
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void txtstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartActionPerformed

    private void txtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtendActionPerformed

    private void chkbxMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxMondayActionPerformed
       String days;
        days="monday";
    }//GEN-LAST:event_chkbxMondayActionPerformed

    private void chkbxWedensdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxWedensdayActionPerformed
         String days;
        days="wedensday";
    }//GEN-LAST:event_chkbxWedensdayActionPerformed

    private void chkbxThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxThursdayActionPerformed
        String days;
        days="thursday";
    }//GEN-LAST:event_chkbxThursdayActionPerformed

    private void chkbxFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxFridayActionPerformed
         String days;
        days="friday";
    }//GEN-LAST:event_chkbxFridayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCncel;
    private javax.swing.JCheckBox chkbxFriday;
    private javax.swing.JCheckBox chkbxMonday;
    private javax.swing.JCheckBox chkbxThursday;
    private javax.swing.JCheckBox chkbxTuesday;
    private javax.swing.JCheckBox chkbxWedensday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAcedemicYear;
    private javax.swing.JLabel lblAcedemicYear1;
    private javax.swing.JLabel lblBellTimes;
    private javax.swing.JLabel lblBooks6;
    private javax.swing.JLabel lblClassDetails;
    private javax.swing.JLabel lblClassDetailsIcon;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblGenerateTimeTable;
    private javax.swing.JLabel lblGenerateTimeTableIcon;
    private javax.swing.JLabel lblSchoolDetails;
    private javax.swing.JLabel lblSchoolDetailsIcon;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblSubjectDetails;
    private javax.swing.JLabel lblSubjectDetailsIcon;
    private javax.swing.JLabel lblTeacherDetails;
    private javax.swing.JLabel lblTeacherDetailsIcon;
    private javax.swing.JLabel lblViewTimeTable;
    private javax.swing.JLabel lblViewTimeTableIcon;
    private javax.swing.JPanel pnlClassDetails;
    private javax.swing.JPanel pnlGenerateTimeTable;
    private javax.swing.JPanel pnlLogOut;
    private javax.swing.JPanel pnlSchoolDetails;
    private javax.swing.JPanel pnlSubjectDetails;
    private javax.swing.JPanel pnlTeacherDetails;
    private javax.swing.JPanel pnlViewTimeTable;
    private javax.swing.JTextField txtAcedemicYear;
    private javax.swing.JTextField txtend;
    private javax.swing.JTextField txtschoolname;
    private javax.swing.JTextField txtstart;
    // End of variables declaration//GEN-END:variables
}
