
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Prabuddi Sathyanka
 */
public class SubjectDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form SubjectDetailsForm
     */
        private final JPopupMenu popupMenu = new JPopupMenu();
    private final JPopupMenu popupMenu2 = new JPopupMenu();
    private JMenuItem menuItem =null;
    
    public SubjectDetailsForm()  {
        
        initComponents();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        Displaysubject ();
        //updateTable ();
          this.setLocationRelativeTo(null);
        this.setSize(950,680);
         createPopupMenu(this);
    }
    
    public void Displaysubject (){
    
    try{        
        PreparedStatement ps;  
        
        String query = "SELECT * FROM `subject`";
        ps = MyConnection.getConnection().prepareStatement(query);
        ResultSet rs =(ResultSet) ps.executeQuery();
        DefaultTableModel subtbl=(DefaultTableModel)tblsubjectDetails.getModel();
          
          subtbl.setRowCount(0);
          
                while(rs.next())
{
   Object o[]={rs.getString("subjectId"),rs.getString("subjectName"),rs.getString("shortName"), rs.getInt("numberOfPeriods"), rs.getInt("numberOfSinglePeriods"),rs.getInt("numberOfDoublePeriods")};
       subtbl.addRow(o);
      
}  
    
    }catch(Exception e){
    
    System.out.println(e.getMessage());
    
    }


    }
  /**public void updateTable() throws ClassNotFoundException, SQLException
 
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        pnlsubjectDetails = new javax.swing.JPanel();
        lblSubjectShortName = new javax.swing.JLabel();
        txtSubjectName = new javax.swing.JTextField();
        lblSubjectName = new javax.swing.JLabel();
        txtSubjectShortName = new javax.swing.JTextField();
        txtSubjectID = new javax.swing.JTextField();
        lblSubjectID = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNumberOfPeriods = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtNumberOfSinglePeriods = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtNumberOfDoublePeriods = new javax.swing.JTextField();
        lblSelectedSubjectID = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCncel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsubjectDetails = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlSchoolDetails = new javax.swing.JPanel();
        lblSchoolDetails = new javax.swing.JLabel();
        lblSchoolDetailsIcon = new javax.swing.JLabel();
        pnlTeacherDetails = new javax.swing.JPanel();
        lblTeacherDetails = new javax.swing.JLabel();
        lblTeacherDetailsIcon = new javax.swing.JLabel();
        pnlSubjectDetails = new javax.swing.JPanel();
        lblSubjectDetails = new javax.swing.JLabel();
        lblSubjectDetailsIcon = new javax.swing.JLabel();
        pnlClassDetails = new javax.swing.JPanel();
        lblClassDetails = new javax.swing.JLabel();
        lblClassDetailsIcon = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlGenerateTimeTable = new javax.swing.JPanel();
        lblGenerateTimeTable = new javax.swing.JLabel();
        lblGenerateTimeTableIcon = new javax.swing.JLabel();
        pnlViewTimeTable = new javax.swing.JPanel();
        lblViewTimeTable = new javax.swing.JLabel();
        lblViewTimeTableIcon = new javax.swing.JLabel();
        pnlLogOut = new javax.swing.JPanel();
        lblBooks6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 890));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlsubjectDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlsubjectDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlsubjectDetails.setPreferredSize(new java.awt.Dimension(463, 210));

        lblSubjectShortName.setText("Short Name");

        txtSubjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectNameActionPerformed(evt);
            }
        });

        lblSubjectName.setText("Subject Name");

        txtSubjectID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectIDActionPerformed(evt);
            }
        });

        lblSubjectID.setText("Subject ID");

        jLabel29.setText("Number Of Periods Per Week");

        jLabel30.setText("Single Periods");

        txtNumberOfSinglePeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfSinglePeriodsActionPerformed(evt);
            }
        });

        jLabel31.setText("Double Periods");

        lblSelectedSubjectID.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlsubjectDetailsLayout = new javax.swing.GroupLayout(pnlsubjectDetails);
        pnlsubjectDetails.setLayout(pnlsubjectDetailsLayout);
        pnlsubjectDetailsLayout.setHorizontalGroup(
            pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubjectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlsubjectDetailsLayout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumberOfDoublePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlsubjectDetailsLayout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addGap(63, 63, 63)
                            .addComponent(txtNumberOfSinglePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSelectedSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlsubjectDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumberOfPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlsubjectDetailsLayout.createSequentialGroup()
                        .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubjectShortName)
                            .addComponent(lblSubjectName)
                            .addComponent(lblSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubjectShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pnlsubjectDetailsLayout.setVerticalGroup(
            pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubjectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectedSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubjectID)
                    .addComponent(txtSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubjectName)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubjectShortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubjectShortName))
                .addGap(18, 18, 18)
                .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtNumberOfPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumberOfSinglePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(pnlsubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberOfDoublePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(214, 197, 214));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Subject Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddNew.setText(" Add New");
        btnAddNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCncel.setText("Cancel");
        btnCncel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCncelActionPerformed(evt);
            }
        });

        tblsubjectDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SubjectID", "Subject Name", "Short Name", "Number Of Periods Per Week", "Number Of Single Periods", "Number Of Double Periods"
            }
        ));
        tblsubjectDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsubjectDetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblsubjectDetails);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlsubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCncel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnAddNew)
                        .addGap(25, 25, 25)
                        .addComponent(btnEdit)
                        .addGap(25, 25, 25)
                        .addComponent(btnDelete)
                        .addGap(25, 25, 25)
                        .addComponent(btnCncel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlsubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel3.setBackground(new java.awt.Color(128, 81, 123));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("School Time Table Generator");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/userIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        pnlSchoolDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSchoolDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSchoolDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSchoolDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSchoolDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSchoolDetails.setText("School Details");
        lblSchoolDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSchoolDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSchoolDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSchoolDetailsMouseClicked(evt);
            }
        });

        lblSchoolDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchoolDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/school.png"))); // NOI18N

        javax.swing.GroupLayout pnlSchoolDetailsLayout = new javax.swing.GroupLayout(pnlSchoolDetails);
        pnlSchoolDetails.setLayout(pnlSchoolDetailsLayout);
        pnlSchoolDetailsLayout.setHorizontalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSchoolDetailsLayout.setVerticalGroup(
            pnlSchoolDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSchoolDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSchoolDetailsLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblSchoolDetails)
                .addGap(20, 20, 20))
        );

        pnlTeacherDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblTeacherDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblTeacherDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblTeacherDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblTeacherDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTeacherDetails.setText("Teacher Details");
        lblTeacherDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTeacherDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTeacherDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTeacherDetailsMouseClicked(evt);
            }
        });

        lblTeacherDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/teacherIcon.png"))); // NOI18N
        lblTeacherDetailsIcon.setText("\n");

        javax.swing.GroupLayout pnlTeacherDetailsLayout = new javax.swing.GroupLayout(pnlTeacherDetails);
        pnlTeacherDetails.setLayout(pnlTeacherDetailsLayout);
        pnlTeacherDetailsLayout.setHorizontalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTeacherDetailsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTeacherDetailsLayout.setVerticalGroup(
            pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTeacherDetailsLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlTeacherDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pnlSubjectDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblSubjectDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblSubjectDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblSubjectDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblSubjectDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubjectDetails.setText("Subject Details");
        lblSubjectDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSubjectDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSubjectDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSubjectDetailsMouseClicked(evt);
            }
        });

        lblSubjectDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubjectDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/sbjectIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlSubjectDetailsLayout = new javax.swing.GroupLayout(pnlSubjectDetails);
        pnlSubjectDetails.setLayout(pnlSubjectDetailsLayout);
        pnlSubjectDetailsLayout.setHorizontalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSubjectDetailsIcon)
                .addGap(18, 18, 18)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubjectDetailsLayout.setVerticalGroup(
            pnlSubjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubjectDetailsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubjectDetailsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlClassDetails.setBackground(new java.awt.Color(102, 0, 102));

        lblClassDetails.setBackground(new java.awt.Color(153, 0, 153));
        lblClassDetails.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblClassDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblClassDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClassDetails.setText("Class Details");
        lblClassDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClassDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblClassDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClassDetailsMouseClicked(evt);
            }
        });

        lblClassDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/classRoomIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlClassDetailsLayout = new javax.swing.GroupLayout(pnlClassDetails);
        pnlClassDetails.setLayout(pnlClassDetailsLayout);
        pnlClassDetailsLayout.setHorizontalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblClassDetailsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClassDetailsLayout.setVerticalGroup(
            pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassDetailsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlClassDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClassDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassDetails))
                .addGap(19, 19, 19))
        );

        lblDashboard.setBackground(new java.awt.Color(204, 204, 255));
        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(204, 204, 204));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setText("Dashboard");

        pnlGenerateTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblGenerateTimeTable.setBackground(new java.awt.Color(153, 0, 153));
        lblGenerateTimeTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblGenerateTimeTable.setForeground(new java.awt.Color(204, 204, 204));
        lblGenerateTimeTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGenerateTimeTable.setText("Generate Time Table");
        lblGenerateTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenerateTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGenerateTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerateTimeTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGenerateTimeTableMouseEntered(evt);
            }
        });

        lblGenerateTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/genarateTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlGenerateTimeTableLayout = new javax.swing.GroupLayout(pnlGenerateTimeTable);
        pnlGenerateTimeTable.setLayout(pnlGenerateTimeTableLayout);
        pnlGenerateTimeTableLayout.setHorizontalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblGenerateTimeTableIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlGenerateTimeTableLayout.setVerticalGroup(
            pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenerateTimeTableLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlGenerateTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGenerateTimeTableIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenerateTimeTable))
                .addGap(19, 19, 19))
        );

        pnlViewTimeTable.setBackground(new java.awt.Color(102, 0, 102));

        lblViewTimeTable.setBackground(new java.awt.Color(153, 0, 153));
        lblViewTimeTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblViewTimeTable.setForeground(new java.awt.Color(204, 204, 204));
        lblViewTimeTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewTimeTable.setText("View Time Table");
        lblViewTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewTimeTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblViewTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewTimeTableMouseClicked(evt);
            }
        });

        lblViewTimeTableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/viewTimeTableIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlViewTimeTableLayout = new javax.swing.GroupLayout(pnlViewTimeTable);
        pnlViewTimeTable.setLayout(pnlViewTimeTableLayout);
        pnlViewTimeTableLayout.setHorizontalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblViewTimeTableIcon)
                .addGap(20, 20, 20)
                .addComponent(lblViewTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlViewTimeTableLayout.setVerticalGroup(
            pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewTimeTableLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlViewTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewTimeTableIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewTimeTable))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlLogOut.setBackground(new java.awt.Color(153, 0, 153));
        pnlLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogOutMouseClicked(evt);
            }
        });

        lblBooks6.setBackground(new java.awt.Color(153, 0, 153));
        lblBooks6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblBooks6.setForeground(new java.awt.Color(204, 204, 204));
        lblBooks6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBooks6.setText("Logout");
        lblBooks6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBooks6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBooks6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBooks6MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iicons/logOutIcon.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogOutLayout = new javax.swing.GroupLayout(pnlLogOut);
        pnlLogOut.setLayout(pnlLogOutLayout);
        pnlLogOutLayout.setHorizontalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogOutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblBooks6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogOutLayout.setVerticalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBooks6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlClassDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
            .addComponent(pnlLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSchoolDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlSubjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlClassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlGenerateTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlViewTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(pnlLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectNameActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        String subjectID = txtSubjectID.getText();
        String subjectname=txtSubjectName.getText();
        String subjectShortname=txtSubjectShortName.getText();     
        int numberOfPeriods = Integer.valueOf(txtNumberOfPeriods.getText());
        int numberOfSinglePeriods = Integer.valueOf(txtNumberOfSinglePeriods.getText());
        int numberOfDoublePeriods = Integer.valueOf(txtNumberOfDoublePeriods.getText());
        
       ResultSet rs = null;
       PreparedStatement ps;       
        
           try {
            String query="INSERT INTO `subject`(`subjectID`,`subjectName`, `shortName`, `numberOfPeriods`,`numberOfSinglePeriods`,`numberOfDoublePeriods`) VALUES (?,?,?,?,?,?)";
             ps = MyConnection.getConnection().prepareStatement(query);
           
             ps.setString(1,subjectID);
             ps.setString(2,subjectname);
             ps.setString(3,subjectShortname);
             ps.setInt(4,numberOfPeriods); 
             ps.setInt(5,numberOfSinglePeriods); 
             ps.setInt(6,numberOfDoublePeriods);             
                   
            
            if(ps.executeUpdate() > 0)
            {
            JOptionPane.showMessageDialog(null,"Subject details added successfully");            
            Displaysubject();
             txtSubjectID.setText(""); 
            txtSubjectName.setText("");
            txtSubjectShortName.setText("");
            txtNumberOfPeriods.setText("");
            txtNumberOfSinglePeriods.setText("");
            txtNumberOfDoublePeriods.setText("");
            }
            
           
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void lblSchoolDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSchoolDetailsMouseClicked
         SchoolDetailsForm sclDetailsForm = null;
        sclDetailsForm = new SchoolDetailsForm();
        sclDetailsForm.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_lblSchoolDetailsMouseClicked

    private void lblSubjectDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubjectDetailsMouseClicked
        // TODO add your handling code here
        SubjectDetailsForm subjectDetailsForm = null;
        subjectDetailsForm = new SubjectDetailsForm();
        subjectDetailsForm.setVisible(true);
        this.setVisible(false); 
        
    }//GEN-LAST:event_lblSubjectDetailsMouseClicked

    private void lblClassDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClassDetailsMouseClicked
        // TODO add your handling code here:
         ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblClassDetailsMouseClicked

    private void lblTeacherDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTeacherDetailsMouseClicked
        // TODO add your handling code here:
        TeacherDetailsForm teacherDetailsForm = new TeacherDetailsForm();
        teacherDetailsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblTeacherDetailsMouseClicked

    private void lblGenerateTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerateTimeTableMouseClicked
        // TODO add your handling code here:
       popupMenu.show(this,150,475);
    }//GEN-LAST:event_lblGenerateTimeTableMouseClicked

    private void lblGenerateTimeTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerateTimeTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGenerateTimeTableMouseEntered

    private void lblViewTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewTimeTableMouseClicked
        // TODO add your handling code here:
         popupMenu.show(this,150,550);
    }//GEN-LAST:event_lblViewTimeTableMouseClicked

    private void pnlLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogOutMouseClicked
         LoginPage lpage = new LoginPage();
            lpage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_pnlLogOutMouseClicked

    private void btnCncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCncelActionPerformed
         Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCncelActionPerformed

    private void lblBooks6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooks6MouseClicked
        
    }//GEN-LAST:event_lblBooks6MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        String selectedSubjectID = lblSelectedSubjectID.getText();
        String subjectID = txtSubjectID.getText(); 
        String subjectname=txtSubjectName.getText();
        String subjectShortname=txtSubjectShortName.getText();     
        int numberOfPeriods = Integer.valueOf(txtNumberOfPeriods.getText());
        int numberOfSinglePeriods = Integer.valueOf(txtNumberOfSinglePeriods.getText());
        int numberOfDoublePeriods = Integer.valueOf(txtNumberOfDoublePeriods.getText());
      
       PreparedStatement ps;       
        
           try {
            String query="UPDATE `subject` SET `subjectID`=?,`subjectName`=?,`shortName`=?,`numberOfPeriods`=?,`numberOfSinglePeriods`=?,`numberOfDoublePeriods`=? WHERE `subjectID`= ?";
             ps = MyConnection.getConnection().prepareStatement(query);           
             ps.setString(1,subjectID);    
             ps.setString(2,subjectname);
             ps.setString(3,subjectShortname);
             ps.setInt(4,numberOfPeriods); 
             ps.setInt(5,numberOfSinglePeriods); 
             ps.setInt(6,numberOfDoublePeriods); 
             ps.setString(7,selectedSubjectID);                   
             //ps.executeUpdate();
             
            if(ps.executeUpdate() > 0)
            {
            JOptionPane.showMessageDialog(null,"Subject details updated successfully");            
            Displaysubject();
            txtSubjectID.setText(""); 
            txtSubjectName.setText("");
            txtSubjectShortName.setText("");
            txtNumberOfPeriods.setText("");
            txtNumberOfSinglePeriods.setText("");
            txtNumberOfDoublePeriods.setText("");
            }            
           
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } 



        
    }//GEN-LAST:event_btnEditActionPerformed

 
    private void tblsubjectDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsubjectDetailsMouseClicked
        // TODO add your handling code here:
                
                   DefaultTableModel tableModel=(DefaultTableModel)tblsubjectDetails.getModel();
                  int myIndex  = tblsubjectDetails.getSelectedRow();  
                  lblSelectedSubjectID.setText(tableModel.getValueAt(myIndex, 0).toString());
                  txtSubjectID.setText(tableModel.getValueAt(myIndex, 0).toString());
                  txtSubjectName.setText(tableModel.getValueAt(myIndex, 1).toString());
                  txtSubjectShortName.setText(tableModel.getValueAt(myIndex, 2).toString());
                  txtNumberOfPeriods.setText(tableModel.getValueAt(myIndex, 3).toString());
                  txtNumberOfSinglePeriods.setText(tableModel.getValueAt(myIndex, 4).toString());
                  txtNumberOfDoublePeriods.setText(tableModel.getValueAt(myIndex, 5).toString());
                  
             
    }//GEN-LAST:event_tblsubjectDetailsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         
        String subjectID = lblSelectedSubjectID.getText();   
      
       PreparedStatement ps;       
        
           try {
            String query="DELETE FROM `subject` WHERE `subjectID`= ?";
             ps = MyConnection.getConnection().prepareStatement(query);           
             ps.setString(1,subjectID);                     
                   
            
            if(ps.executeUpdate() > 0)
            {
            JOptionPane.showMessageDialog(null,"Subject details deleted successfully");            
            Displaysubject();
            lblSelectedSubjectID.setText("");
            txtSubjectID.setText(""); 
            txtSubjectName.setText("");
            txtSubjectShortName.setText("");
            txtNumberOfPeriods.setText("");
            txtNumberOfSinglePeriods.setText("");
            txtNumberOfDoublePeriods.setText("");
            }            
           
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } 
            
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSubjectIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectIDActionPerformed

    private void txtNumberOfSinglePeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfSinglePeriodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfSinglePeriodsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectDetailsForm().setVisible(true);
            }
        });
    }
  private void createPopupMenu(JFrame frame){
        
    menuItem = new JMenuItem(  "Master time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
       // TeacherDetailsForm teacherDetailsForm = new TeacherDetailsForm();
      //  jPanel3.setVisible(true);
                    
       
                }
       
    });
        
        
    menuItem = new JMenuItem(  "Teacher wise time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
                   
                     // jPanel3.setVisible(true);
       
                }
       
    });
  
    
      menuItem = new JMenuItem(  "Class wise time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
        ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
       
                }
    
       
    });
        menuItem = new JMenuItem(  "Create Master time table");
    
    menuItem.addActionListener(new ActionListener(){
        @Override
                public void actionPerformed(ActionEvent e)
                {
        ClassDetails classDetailsForm = new ClassDetails();
        classDetailsForm.setVisible(true);
       
                }
    
       
    });
       
     
     popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Master time table");
     popupMenu.add(menuItem);
    
      popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Teacher wise time table");
     popupMenu.add(menuItem);
    
      popupMenu.add(menuItem);
    
    menuItem = new JMenuItem(  "Class wise time table");
     popupMenu.add(menuItem);
    
        menuItem = new JMenuItem(  "Master time table");
     popupMenu2.add(menuItem);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCncel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBooks6;
    private javax.swing.JLabel lblClassDetails;
    private javax.swing.JLabel lblClassDetailsIcon;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblGenerateTimeTable;
    private javax.swing.JLabel lblGenerateTimeTableIcon;
    private javax.swing.JLabel lblSchoolDetails;
    private javax.swing.JLabel lblSchoolDetailsIcon;
    private javax.swing.JLabel lblSelectedSubjectID;
    private javax.swing.JLabel lblSubjectDetails;
    private javax.swing.JLabel lblSubjectDetailsIcon;
    private javax.swing.JLabel lblSubjectID;
    private javax.swing.JLabel lblSubjectName;
    private javax.swing.JLabel lblSubjectShortName;
    private javax.swing.JLabel lblTeacherDetails;
    private javax.swing.JLabel lblTeacherDetailsIcon;
    private javax.swing.JLabel lblViewTimeTable;
    private javax.swing.JLabel lblViewTimeTableIcon;
    private javax.swing.JPanel pnlClassDetails;
    private javax.swing.JPanel pnlGenerateTimeTable;
    private javax.swing.JPanel pnlLogOut;
    private javax.swing.JPanel pnlSchoolDetails;
    private javax.swing.JPanel pnlSubjectDetails;
    private javax.swing.JPanel pnlTeacherDetails;
    private javax.swing.JPanel pnlViewTimeTable;
    private javax.swing.JPanel pnlsubjectDetails;
    private javax.swing.JTable tblsubjectDetails;
    private javax.swing.JTextField txtNumberOfDoublePeriods;
    private javax.swing.JTextField txtNumberOfPeriods;
    private javax.swing.JTextField txtNumberOfSinglePeriods;
    private javax.swing.JTextField txtSubjectID;
    private javax.swing.JTextField txtSubjectName;
    private javax.swing.JTextField txtSubjectShortName;
    // End of variables declaration//GEN-END:variables

    private static class st {

        private static ResultSet executeQuery(String sql) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public st() {
        }
    }

    private static class model {

        private static void addRow(Object[] columnData) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public model() {
        }
    }
}
